spring:
  application:
    name: user-service
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testuserservice
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: ecom
    password: ecom
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



server:
  port: 8082

