spring:
  application:
    name: order-service
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    url: jdbc:h2:mem:test
  #  jpa:
  #    hibernate:
  #      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ecom
    password: ecom
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083


logging:
  level:
    web: debug